platform :ios, '8.0'

target 'gzmObject' do
pod 'Reveal-iOS-SDK'
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 1.0.1'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.8'
pod 'SDWebImage', '~> 3.8.1'
pod ‘UMengUShare/Social/ReducedQQ'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/ReducedWeChat'
end
